INSERT INTO season (name) VALUES ('FALL'),('SPRING'),('SUMMER'),('WINTER');
INSERT INTO hunt_type (type) VALUES ('BOW'),('MUZZLELOADER'),('RIFLE');
INSERT INTO animal (name) VALUES ('BISON'),('BULL ELK'),('COUES DEER'),('COW ELK'),('MOUNTAIN LION'),('MULE DEER'),('TURKEY');