language: java
jdk:
  - oraclejdk8
sudo: true
script: mvn clean package
deploy:
  provider: elasticbeanstalk
  access_key_id: $ACCESSKEYID
  secret_access_key:
    secure: "$SECRETACCESSKEY"
  region: "us-east-1"  
  app: "guidepro"
  env: "guidepro-dev"
  bucket_name: "elasticbeanstalk-us-east-1-996328651507"
  skip_cleanup: true
on:
  branch: master